spring:
  application:
    name: flashcards-api
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:flashcards;DB_CLOSE_DELAY=-1}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:password}
    driverClassName: ${DATABASE_DRIVER:org.h2.Driver}
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
app:
  security:
    jwt:
      secret: ${JWT_SECRET:very-long-and-secure-secret-key-at-least-256-bits}
    client-id: ${CLIENT_ID:client-id}
    client-secret: ${CLIENT_SECRET:client-secret}
